### ISSUE TITLE
[Question]: Create new environment for RTS

### ISSUE THREAD

**Issue by aleSuglia** [facebookresearch/ELF#37]
Hi there,

I am writing this issue in order to understand if it is possible to create a new environment in ELF by exploiting a game level editors or if it is necessary to implement it by using the C++ API. 

In both cases, could you please suggest the best practices about how to create a new environment that can be easily integrated in your platform?

Thank you so much for your help.

Alessandro

**Comment by yuandong-tian** [comment]
1. If you want to plug-in a completely new environment, then
(1) If it has C/C++ interface, then use the C++ API of ELF (like `./atari` folder)
(2) If it has a python interface (like OpenAI Gym), then use `elf_python` that provides you with a python interface. Note that it is still in its alpha release, so there could be issues. 

2. If you want to reuse the existing RTS engine (`./rts`), then you need to edit C++ code to change map/units to fit your needs (like what we did in `./rts/game_MC`, you can take a look for reference). We are thinking about a LUA interface so that anyone can plug-in a customized game, while still keeping the simulation speed.
